const CartActionType = {
  TOGGLE_HIDDEN_CART: "TOGGLE_HIDDEN_CART",
  ADD_ITEM: "ADD_ITEM",
  CLEAR_ITEM_FROM_CART: "CLEAR_ITEM_FROM_CART",
  REMOVE_ITEM: 'REMOVE_ITEM',
};

export default CartActionType;
